### ISSUE TITLE
Black letters invisible

### ISSUE THREAD

**Issue by Porrumentzio** [ipbc-dev/peertube-theme-bittube-dark-mode#4]
Some letters are in black, most of all on instance's About page, and they are almost invisible:
![irudia](https://user-images.githubusercontent.com/61913683/100541805-968f3800-3246-11eb-9290-bd433a730eed.png)

The color of those letters should be changed

**Comment by cabaleiro8** [comment]
Fixed in version 2.1.2 in bittube-dark-mode and version 2.1.3 in bittube-dark-mode-no-background (can take 1-2 days to be updated at npm & peertube). Thanks for reporting @Porrumentzio!! :+1:

**Comment by Porrumentzio** [comment]
Thanks! Now it looks great!

**Comment by Porrumentzio** [comment]
It still happens on "thumb up/down" buttons, at least on `bittube-dark-mode-no-background`:
![irudia](https://user-images.githubusercontent.com/61913683/102994463-67a37380-451f-11eb-83fc-51e5e286cc2b.png)
